/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorsesIndexRouteImport } from './routes/horses.index'
import { Route as HorsesHorseIdRouteImport } from './routes/horses_.$horseId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIndexRoute = HorsesIndexRouteImport.update({
  id: '/horses/',
  path: '/horses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesHorseIdRoute = HorsesHorseIdRouteImport.update({
  id: '/horses_/$horseId',
  path: '/horses/$horseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses': typeof HorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/horses_/$horseId': typeof HorsesHorseIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/health'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/team'
    | '/horses/$horseId'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions'
    | '/health'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/team'
    | '/horses/$horseId'
    | '/horses'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/health'
    | '/login'
    | '/notifications'
    | '/register'
    | '/settings'
    | '/team'
    | '/horses_/$horseId'
    | '/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  HorsesHorseIdRoute: typeof HorsesHorseIdRoute
  HorsesIndexRoute: typeof HorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/': {
      id: '/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof HorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses_/$horseId': {
      id: '/horses_/$horseId'
      path: '/horses/$horseId'
      fullPath: '/horses/$horseId'
      preLoaderRoute: typeof HorsesHorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  HorsesHorseIdRoute: HorsesHorseIdRoute,
  HorsesIndexRoute: HorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
